# Generated by Django 3.2 on 2022-10-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'Lifestyle'), ('sport', 'Sport'), ('travels', 'Travels'), ('skeping', 'Skeping'), ('fashion', 'Fashion'), ('night party', 'Night Party'), ('see beach', 'See Beach'), ('technology', 'Technology'), ('corporate', 'Corporate'), ('event time', 'Event Time'), ('politics', 'Politics')], max_length=100, null=True),
        ),
    ]
